steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/pratiktest/gcp-cd-codelab"]
    env: ["PROJECT_ROOT=github.com/pratiktest/gcp-cd-codelab"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/proud-amphora-219504/gcp-cd-codelab:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/ proud-amphora-219504/gcp-cd-codelab:$REVISION_ID"
